### ISSUE TITLE
Ability to upload files not in workspace

### ISSUE THREAD

**Issue by tonglil** [drone-plugins/drone-google-cloudstorage#10]
Currently it doesn't seem possible to reference files outside of the workspace for uploading, in `/drone/` for example.

`workspace.Path` is joined to the source:
- https://github.com/drone-plugins/drone-google-cloudstorage/blob/master/main.go#L226
- https://github.com/drone-plugins/drone-google-cloudstorage/blob/release/0.4/main.go#L226.

**Comment by tboerger** [comment]
Of course not, because the workspace folder is the only path that gets shared between the build steps, so you don't get access to any other folder.

**Comment by tonglil** [comment]
Wait, but the `/drone/` directory is also shared between the build steps (and subsequently [things in there are can get cached](http://readme.drone.io/0.4/usage/caching/#common-issues)), not just `/drone/src/github.com/org/name`.

**Comment by tonglil** [comment]
Could I get some clarification on this? I would like to avoid maintaining a fork of this plugin.

**Comment by tonglil** [comment]
```json
 "workspace": {
        "root": "/drone/src",
        "path": "/drone/src/github.com/octocat/hello-world",
        "keys": {
            "private": "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQC..."
        }
    },
```

**Comment by tboerger** [comment]
/drone is the workspace root, and this path is the only one you can upload

**Comment by tonglil** [comment]
Thank you for responding.

Is `workspace.Root` not shared between build steps?

**Comment by tboerger** [comment]
The root is shared between all steps and files within the root can be copied
